CC=/home/stufox/workspace/luckfox-pico/tools/linux/toolchain/arm-rockchip830-linux-uclibcgnueabihf/bin/arm-rockchip830-linux-uclibcgnueabihf-gcc

TARGET=fb_fill_color
SRCS=fb_fill_color.c

all:
	$(CC) -o $(TARGET) $(SRCS)

clean:
	rm -f $(TARGET)
